notifications:
  commits:              commits@infra.apache.org
  pullrequests:         commits@infra.apache.org
  issues:               issues@infra.apache.org
  discussions:          issues@infra.apache.org

github:
  features:
    # Enable issue management
    issues: true
